### ISSUE TITLE
篩選函式

### ISSUE THREAD

**Issue by b03201003** [SystemProgrammingatNTU/mp4-discussion#11]
關於篩選函式這部分
是讀取"filter_function":後面的內容
然後另外寫成一個檔案並進行編譯再載入嗎
那個寫了filter_function的檔案會有需要include些什麼嗎

**Comment by MROS** [comment]
僅需包含 struct User 。

**Comment by tall15421542** [comment]
想要請問一下助教，我剛剛測試了一下，確認了不需要include函式庫這件事。比如說strlen或malloc，我在主程式與動態編譯的函式庫裡都沒有include <string.h> 與 <stdlib.h>，為什麼可以這樣～函式庫是在哪個階段把這兩個函式庫引進來了～

**Comment by MROS** [comment]
gcc 會自己去鏈結標準函式庫，換成 g++ 就不行了。
當然，不主動 include 要使用的標頭檔是不良實踐，而我測試時也不會用到任何函式庫。
