### ISSUE TITLE
動態編譯匹配函式

### ISSUE THREAD

**Issue by tall15421542** [SystemProgrammingatNTU/mp4-discussion#12]
Dlopen是打開一個已經編譯好的函式庫，那麼要如何在server端的程式裡編譯一個已經寫入struct user與match function的檔案呢？不知道有沒有相關的關鍵字可以幫助我學習這件事，謝謝助教～

**Comment by MROS** [comment]
用 system 函式去調用 gcc ，應該是最簡單的做法。
