### ISSUE TITLE
匹配算法與平行 與分割JSON

### ISSUE THREAD

**Issue by tall15421542** [SystemProgrammingatNTU/mp4-discussion#13]
想要請問助教，若有一個很耗時的匹配函示正在匹配中，此時客戶端傳了一個try match指令。所以現在有兩個fork出去的process，一個正在處理匹配，一個在等他完成匹配後才開始匹配。因為fork之後的記憶體是獨立的，所以等匹配完成後的佇列，在等待中的那個process並不知道，目前想法是可以利用檔案去溝通這件事。但是另一個問題是，兩個child process要怎麼溝通，也就是等待中的process如何得知另一個process已經匹配完成了。

另外想要請問一下分割JSON，想要請問這一次的作業，在什麼樣的情境下會使用到分割JSON呢？因為一次傳送的訊息至多不過幾千字元，socket的buffer應該是足夠的吧？那如果要分割，是要分割成什麼什麼形式，spec所提的邏輯是什麼，想要問助教有沒有類似的範例～謝謝助教！

**Comment by MROS** [comment]
首先我不建議讓兩個子程序間進行溝通，當子程序很多時會很複雜，此時透過主程序來居中協助溝通的話，模型會比較簡單。

所謂的 JSON 分割，是指不同個 JSON 之間是有東西隔開的。socket 中一個 send 指令未必對應於一個 recv 指令，甚至我一次 send 就可以包含多條 JSON，因此需要某種方式來將不同指令隔開。

還有不瞭解的，可以繼續與我討論。

**Comment by timlee0119** [comment]
助教您好，不好意思我不太理解什麼情況下client會一次send多條json，不論是try_match, send_message或是quit，client在送出一條json指令後不是應該都要等server回傳確認的json信息嗎?

**Comment by MROS** [comment]
send_message 不會改變狀態，所以未必會等待確認訊息。

即使不考慮一次 send 多條 json ，我也可以故意使用多次 send 才送出一個完整 JSON（或者 TCP 會自動切割） ，總而言之，在現實世界中，假設一次 send 對應到一次 recv ，是不切實際的。
