### ISSUE TITLE
server 回傳格式的問題

### ISSUE THREAD

**Issue by sea120424** [SystemProgrammingatNTU/mp4-discussion#14]
一開始client輸入 /t 開始連線後server回傳的格式要怎麼寫呢？
直接用cJson打是
{
        "cmd":  "try_match"
}
好像是不對的。

**Comment by MROS** [comment]
您的 server 送出的 JSON 字串是否含有換行呢？

**Comment by sea120424** [comment]
我server 送出的格式是這樣

cJSON *pJsonRoot = cJSON_CreateObject();
cJSON_AddStringToObject(pJsonRoot, "cmd", "try_match");
char *p = cJSON_Print(pJsonRoot);

也有試過直接回傳
{"cmd": "try_match"}
和 
"cmd": "try_match"
可是都沒有成功，把client一開始送的字串直接回傳卻會成功

**Comment by MROS** [comment]
你的 JSON 尾部需要加上換行。

**Comment by sea120424** [comment]
尾部是指
{
"cmd": "try_match"
}\n
嗎

**Comment by MROS** [comment]
不太確定你上面的 { 之後有沒有換行，不模糊的表示法是這樣
```
 {"cmd":"try_match"}\n
```

**Comment by sea120424** [comment]
了解，
謝謝助教
