### ISSUE TITLE
關於CPU檢測以及篩選函式平行

### ISSUE THREAD

**Issue by acnokego** [SystemProgrammingatNTU/mp4-discussion#15]
之前有人問到怎麼評分CPU平行化,
助教有回答說會先行量測這些複雜函式直接執行所需的時間後，再去估算同學的平行化程度.

這邊想再詳細了解, 如果要通過平行化的檢測, 是指要量測擁有這個複雜函數的client 從開始match到match到後所花的時間至少要比直接執行的時間還要短嗎? 

因為目前自己想到的方式是不同的client執行try_match時各fork 一個 child process, 且後到的要等先到的client跑完try_match, 但這樣感覺單一個client在篩選函式所花的時間似乎是沒有變比較快, 因為每個client還是要比對完目前正在等待match 的人.  
想請問我這樣的想法是對的嗎?是否需要調整一些實作的方式才能通過檢測?
謝謝!

**Comment by MROS** [comment]
測試時會同時有非常多個客戶端進行 try_match ，所以量測的會是一堆客戶端全部匹配完成所花費的時間。

你的做法似乎沒有達到任何平行化？注意到多個客戶端可以同時去匹配正在等待 match 的人。

此外對於每個 client 都 fork 一個子程序，當千人上線時也許會導致效能問題。
