### ISSUE TITLE
MP4會用到multi thread嗎

### ISSUE THREAD

**Issue by timlee0119** [SystemProgrammingatNTU/mp4-discussion#16]
助教您好，想請問一下這次的作業如果不用到multi thread一般來說是會有辦法完成的嗎?
還是一定會需要練習到那部份呢? 感謝助教回答

**Comment by MROS** [comment]
不一定需要，multithread 可以協助你完成某些邏輯，或是在局部進行加速，然而完全採用 multiproess 依然能夠達到加速的標準。

**Comment by timlee0119** [comment]
了解 謝謝助教，另外想請問一下作業要求中server要綁定於0.0.0.0，意思是在設定sockaddr的IP時應該要用
serverAddr.sin_addr.s_addr = inet_addr("0.0.0.0")
而非socket教學頁中的
server_addr.sin_addr.s_addr = INADDR_ANY;
嗎? 不知道理解有沒有錯誤 感謝助教

**Comment by MROS** [comment]
INADDR_ANY 即代表 0.0.0.0 。
若你設定爲 127.0.0.1 ，就僅能在本機上連接到伺服器，但測試時客戶端可能會在其他機器上發起連線到伺服器。
