### ISSUE TITLE
Open file limits

### ISSUE THREAD

**Issue by tsunghan-wu** [SystemProgrammingatNTU/mp4-discussion#18]
請問助教open file limits是多少呢？
由於我想要fork出4個child process
因此在1000個clinets同時上線的時候
會需要3(最基本的)+4*2(pipe)+1(socket)+1000(clients)+1(system gcc用)再加上本來登入工作站就會跑的東西
這樣就極度接近1024的limits了
(好啦事實上就是我開到994個client沒有爆掉，但開了996~1000個client就爆了www)
error message有提到"too many open files"
想請問助教這個該怎麼解決呢？

**Comment by MROS** [comment]
這還滿有意思的，我原本預估 1024 -1000 有 24 個連線做其他事應該夠了，你知道你最大的 fd 是多少嗎？是否有沒有關閉的連線？

**Comment by tsunghan-wu** [comment]
確定該關的都關掉了
我用$ulimit -a檢查發現最大1024
我檢查了這個process沒有用到1024個fd，可是ulimit應該是以一個user計算的，估計是這個process要+1，然後ssh工作站pam驗證等等有process要開(?
而且我驗證過了我只差這幾個因為開成單進程就過了
不過有同學是沒問題的過了所以我想問一下

**Comment by tsunghan-wu** [comment]
主要應該是因為平行的時候，如果開4個process同步，最糟糕的時候每個process做兩次dlopen，這樣算起來1024不可能過的了

**Comment by MROS** [comment]
ulimit 應該是以一個 process 在計算的，會不會是你 fork 出來的子程序繼承了父程序的 fd ，又再打開更多 fd 才造成這個現象？

**Comment by jerry73204** [comment]
理論上 file descriptor 沒用滿不應該有這樣的問題，先檢查看看是不是有file descriptor leak
，像是 netstat -n 有沒有出現很多 CLOSE_WAIT ，或者用 lsof 列 open files。

**Comment by tsunghan-wu** [comment]
好的謝謝助教
我再研究研究

**Comment by tsunghan-wu** [comment]
助教我覺得這個上屆真的有點太緊了
我自己撰寫了一個測試程式如下：
(file name = test.cpp)
```
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <assert.h>
#include <string>
using namespace std;
int main(){
	char tmp[] = "XDDDD";
	for(int i = 0; i < 1007; i++){
		string cur = tmp + to_string(i);
		int fd = open(cur.c_str(), O_WRONLY | O_CREAT, 0644);

	}
	string cmd = "g++ test.cpp -o QAQ";
	system(cmd.c_str());
}
```
在執行$./a.out的時候
由於在呼叫system幫我們編譯程式的時候，系統會會開啟所有include的檔案
(估計是真的碰到了1024)
因此大約在1007-1110之間他就會顯示下面的error訊息
/usr/bin/ld: 找不到 /usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/crtendS.o: Too many open files
雖然說編譯我們的篩選函式可能用助教你說的gcc的編譯參數可能不會調用那麼多，但這個上屆我覺得還是太緊了
因此假設我們要做到平行，至少開兩個child process並且要以fifo溝通，那麼：
1000(client)+3(stdin, stdout, stderr)+4(2*2pipe)+1(socket)其實就已經到達上限了
總結以上，我覺得1000個client真的有點多 
不知道助教怎麼看？
痾還是我還是哪裡寫錯了QQ
因為我自己測的話如果是開兩個child process，998會過但是1000會死QQ在一個臨界值的概念orz

**Comment by MROS** [comment]
可否如下試著使 fd 能夠在執行時關閉（close-on-exec）？如果還是覺得太緊，我可以考慮放寬。
``` cpp
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <assert.h>
#include <string>
using namespace std;
int main(){
	char tmp[] = "XDDDD";
	for(int i = 0; i < 1007; i++){
		string cur = tmp + to_string(i);
		int fd = open(cur.c_str(), O_WRONLY | O_CREAT, 0644);

		int flags = fcntl(fd, F_GETFD);
		flags |= FD_CLOEXEC;
		fcntl(fd, F_SETFD, flags);
	}
	string cmd = "g++ test.cpp -o QAQ";
	system(cmd.c_str());
}
```

**Comment by tsunghan-wu** [comment]
助教不好意思
額......我覺得有點太緊了
我查了有關於close-on-exec結果如下:
It sets the close-on-exec flag for the file descriptor, which causes the file descriptor to be automatically (and atomically) closed when any of the exec-family functions succeed.
我這樣弄還是掛了
我猜助教你用message queue不會炸
只是像我開個fifo用掉那些fd真的有點抖
再加上select的東西實在不敢暫時關起來
因此請求能否放寬？

**Comment by MROS** [comment]
雖然我覺得應該可以處理，但好吧！不希望同學們被這個限制困住。

我將把最大上線人數調整至 800 人，之後會寄信通知所有同學。
