### ISSUE TITLE
關於fork

### ISSUE THREAD

**Issue by ghost** [SystemProgrammingatNTU/mp4-discussion#20]
助教好
請問可以在make的時候生成其他程式，然後在fork之後exec他嗎？

**Comment by MROS** [comment]
不可以，我會將你的 inf-bonbon-server 搬到一個空目錄，你將無法以相對路徑擷取另一個外部程式

**Comment by ghost** [comment]
所以只能exec inf-bonbon-server自己?

**Comment by MROS** [comment]
如果硬要使用 exec ，確實能夠 exec 自己，但應該以 fork 來做就可以了。
