### ISSUE TITLE
儲存動態函式庫的函式

### ISSUE THREAD

**Issue by timlee0119** [SystemProgrammingatNTU/mp4-discussion#21]
助教您好，想請問一下該如何正確的儲存動態函式庫的函式，以供client在try_match時能直接把他的User struct丟進去等待佇列中用戶的篩選函式，而不用每次都重新編譯queue裡面用戶的篩選函式（感覺這樣效能上會太差？）
我目前的做法是，每當一個client在try_match時找不到人配對，就把它dlsym出來的function pointer存起來，想要給以後配對的人不用編譯直接用。但這樣會產生一個問題：function pointer貌似不能動態配置記憶體，所以在scope結束後，pointer指向的function就會被清除，導致沒辦法儲存該function；況且dlclose以後原本儲存的function pointer也會不能用，那這樣到底該怎麼儲存動態函式庫的函式呢？
或是其實根本不需要儲存曾經編譯過的client的篩選函式，也可以達到良好的配對效能呢？如果是這樣的話能否請助教提供一些小方向QQQQ
抱歉文長，感謝助教的耐心閱讀

**Comment by MROS** [comment]
將函式編譯成爲動態函式庫，之後只要載入，無需再編譯。
至於避免重複載入可能不容易做到，但只要避免掉重複編譯，效能大概不會有太大問題。
