### ISSUE TITLE
先來先到原則

### ISSUE THREAD

**Issue by oopzzozzo** [SystemProgrammingatNTU/mp4-discussion#22]
"請在不違反先來先到原則的狀況下進行平行化，也就是說，平行化之後的行爲與「一個人從頭試到尾，再換下一個人試」的行爲相同。"

請問這邊的"行為"有包含"收到matched的順序"嗎？還是只論match到的對象？

舉例：
client1 try_match, client1 進入 queue
client2 try_match, client2與client1不匹配, client2 進入 queue
client3 try_match, client3與client1不匹配,當client3與client2還在進行匹配時...
client4 try_match, client4與client1匹配了!!
這時我們可以直接把client4跟client1送作堆嗎？
（顯然不管client3與client2有沒有匹配成功，client4跟client1都會在一起）
還是說一定要先回覆client3,client2（匹配到的話）才可以回覆client4,client1？

**Comment by MROS** [comment]
可以先回覆client4, client1
