### ISSUE TITLE
能否修改filter function編譯時的參數-std=c11

### ISSUE THREAD

**Issue by chu0802** [SystemProgrammingatNTU/mp4-discussion#23]
想用c++寫這次的作業
在filter function的介紹部份
助教給的編譯參數是
gcc -fPIC -O2 -std=c11 [filter_function].c -shared -o [share_lib_name].so

如果我想用c++寫這次的作業
把編譯參數改成
g++ -fPIC -O2 -std=c++11 [filter_function].cpp -shared -o [share_lib_name].so
是可以的嗎
還是動態函式庫的實作有用到-std=c11的哪些標準 ，不能任意修改？

另外想問同時使用cin cout跟scanf/printf/write/read 會不會出甚麼狀況？
因為之前好像有過混用，導致io的順序跟預期不一樣的情況......

**Comment by MROS** [comment]
不確定是否有問題，但 c++11 並沒有完全包含 c11 ，因此建議還是使用 gcc 來編譯。
這麼做並不影響你使用 C++ 來寫這次作業。

緩衝區可能不一致導致最後輸出結果不同，但本次只看 socket 的輸入輸出，故不會有問題。
