### ISSUE TITLE
把User加上typedef

### ISSUE THREAD

**Issue by nobel861017** [SystemProgrammingatNTU/mp4-discussion#24]
typedef struct user {
	char name[33];
	unsigned int age;
	char gender[7];
	char introduction[1025];
} User;
把User加上typedef是ok的嗎？

**Comment by MROS** [comment]
如果你是要把它跟 filter_function 一起編譯的話，似乎不太 ok

**Comment by nobel861017** [comment]
喔喔沒有
filter function還是用原來的格式編譯
只是inf-bonbon-server.cpp裡面我不想一直寫struct User

**Comment by MROS** [comment]
那不會有問題，其實你如果是用 C++ ，不需要 typedef 就能直接寫 User 了。
