### ISSUE TITLE
動態連結函式問題

### ISSUE THREAD

**Issue by shihkaiho** [SystemProgrammingatNTU/mp4-discussion#25]
假設我已經有個函式sub.c
`$cat sub.c`
`int sub(int a, int b){return (a - b);}`

然後我在其他程式內執行:
`system("g++ -fPIC -shared sub.c -o libsub.so");`
系統跑出找不到libsub.so
但是如果使用
`system("gcc -fPIC -shared sub.c -o libsub.so");`
就OK了
所以動態函式只能用gcc編嗎?
有沒有用g++編的方案?

**Comment by MROS** [comment]
我使用 g++ 是可以編譯的。此外不管你是用 gcc 還是 g++ 編譯，都可以用 dlopen 來開啓。

**Comment by shihkaiho** [comment]
![image](https://user-images.githubusercontent.com/26343386/34321812-67345a04-e852-11e7-8cc8-748a762b74db.png)
不知道助教可不可以幫看><
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <dlfcn.h>
#include <assert.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
char sub_function_code[] = "int sub(int a, int b){return (a - b);}";
int main()
{
    int fd = open("sub.c", O_CREAT | O_WRONLY | O_TRUNC, 0666);
    write(fd, sub_function_code, strlen(sub_function_code));
    close(fd);
    system("g++ -fPIC -shared sub.c -o libsub.so");
    void* handle = dlopen("./libsub.so", RTLD_LAZY);
    dlerror(); /* Clear any existing error */
    int (*sub)(int, int) = (int (\*)(int, int)) dlsym(handle, "sub");
    printf("sub: %d\n", sub(9,2));
    dlclose(handle);
    return 0;
}

**Comment by MROS** [comment]
首先你給出的範例程式有些 bug ，建議進行修改。

C++ 由於支援函式重載，也就是說，同名函式可以有多個型別，在二進位檔中不會單單記錄函式的名稱（符號），因此 dlsym 會無法找到 sub ，建議你使用 gcc 來進行編譯就好，若想避免上述問題，你可以採用
```
extern "C" int sub(int a, int b){return (a - b);}
```

**Comment by a127000555** [comment]
把你的code 加上extern "C"，也就是
char sub_function_code[] = "extern \"C\" int sub(int a, int b){return (a - b);}";
就找的到symbol了><
