### ISSUE TITLE
有關傳JSON

### ISSUE THREAD

**Issue by drevil5678** [SystemProgrammingatNTU/mp4-discussion#26]
請問助教
會不會有一個client先寄"cmd = try_match"
然後過了10分鐘才把剩下的傳完
(這10分鐘有其他client傳訊息過去給server)
這樣的情況要怎麼處理呢
謝謝助教

**Comment by MROS** [comment]
你意思是說他只傳了cmd 但是其餘的基本資料要等十分鐘才能傳過來嗎。

**Comment by drevil5678** [comment]
嗯嗯 對

**Comment by MROS** [comment]
是不太可能間隔這麼久，但有可能有間隔，此時就得先將收到的訊息緩存起來。
