### ISSUE TITLE
c++寫這次的作業

### ISSUE THREAD

**Issue by chu0802** [SystemProgrammingatNTU/mp4-discussion#27]
抱歉 還是不太理解怎麼混用c++寫這次的作業
1. filter function可以用c++完成嗎 如果可以 還能用gcc編譯嗎
2. 看起來我寫inf-bonbon-server.cpp的時候，用g++去編譯，會有錯誤情況
/tmp/ccDroqXA.o: 於函式 main:
inf-bonbon-server.cpp:(.text.startup+0x2b): 未定義參考到「dlopen」
inf-bonbon-server.cpp:(.text.startup+0x3c): 未定義參考到「dlerror」
inf-bonbon-server.cpp:(.text.startup+0x49): 未定義參考到「dlsym」
inf-bonbon-server.cpp:(.text.startup+0x4e): 未定義參考到「dlerror」
inf-bonbon-server.cpp:(.text.startup+0x76): 未定義參考到「dlclose」

可是我有include範例裡的所有標頭檔，編譯參數也有加上-ldl，這樣是為甚麼呢
我的編譯參數是
g++ -std=c++11 -ldl -g -O2 inf-bonbon-server.cpp -o inf-bonbon-server

**Comment by a127000555** [comment]
雖然我不知道確切原因，不過我也遇過你這種情況：把 -ldl的參數搬到最後面就過了

**Comment by MROS** [comment]
1. 篩選函式一定會符合c11標準，然而符合c11未必會符合c++11。

2. 鏈接的參數必須置於欲編譯的檔名之後
