### ISSUE TITLE
用戶try_match時包含惡意函式or無法編譯時server的行為

### ISSUE THREAD

**Issue by timlee0119** [SystemProgrammingatNTU/mp4-discussion#29]
如題，想請問這種情況下server應該是要讓他一直在try_match佇列中，但是配對不到任何人，這樣的理解有誤嗎？
感謝助教

**Comment by MROS** [comment]
首先，不會有無法編譯的情形。
再來，你不能判斷惡意程式真的每次都會 crash ，有可能一下子 crash 一下子又回傳 1

**Comment by timlee0119** [comment]
但是SPEC上面有寫: 若編譯時發生錯誤（gcc 返回值不爲 0），或是執行時進程崩潰，也算成未通過篩選。
所以其實測試時並不會有無法編譯的filter function來try match嗎?

**Comment by MROS** [comment]
不會，已經補在測試的保證上了
