### ISSUE TITLE
關於惡意篩選函式

### ISSUE THREAD

**Issue by acnokego** [SystemProgrammingatNTU/mp4-discussion#3]
想請問, 若是child process因為某個client的惡意篩選函式crash了之後, 該client的狀態是會回到閒置狀態嗎?
還是要以甚麼方式再去處理該client的try match 
謝謝~

**Comment by MROS** [comment]
在篩選函式一節中有約略提到，編譯失敗或篩選函式導致崩潰，都等同於該篩選函式回傳0，無法匹配。

也就是說，即使篩選函式導致過崩潰，依然得繼續嘗試用下一個人匹配，篩選函式有可能在某些狀況下崩潰，而在其他狀況下返回成功匹配的回傳值。
