### ISSUE TITLE
匹配算法 關於違反？

### ISSUE THREAD

**Issue by hengzhichin** [SystemProgrammingatNTU/mp4-discussion#30]
匹配算法採先來先到

若等待隊列中沒有任何人，則該使用者進入等待隊列等候
若等待隊列中有人，則從隊伍頭部開始往後一一嘗試配對
一配對成功，其配對對象脫離等待隊列，一同進入聊天狀態
若全數配對失敗，則進入隊列尾巴等候
請在不違反先來先到原則的狀況下進行平行化，也就是說，** 平行化之後的行爲與「一個人從頭試到尾，再換下一個人試」** 的行爲相同

====

助教你好，請問以下這兩種會違反嗎？

1.

1,2,3,4,5依序進入等待隊列

這時把1 （最先到）拉出做匹配

嘗試2,3,4,5 

若已知1,2可以匹配，但基於1,3的匹配先回傳，

請問可以用1,3拉出一起當對象嗎？而不用1,2嗎？

2.

1,2,3,4,5依序進入等待隊列

1嘗試2,3,4,5皆不合

1放到最後的隊列 2,3,4,5,1

此時輪到2的階段，

2嘗試3,4,5時，皆不合，

突然6進入等待隊列

2,3,4,5,1,6 

由於還是2嘗試匹配別人的階段，發現2,6是可以的

但基於**匹配算法採先來先到**

是否還是要先 1,6 嘗試呢？（如1,6 其實可以的）

因為1最先到？

======

又或者，是指 「拉出嘗試」的人是 「先來先到」？

如  1,2,3,4,5 在等待隊列

那，只要保證1,2,3,4,5 依序拉出匹配就好？

====

**若全數配對失敗，則進入隊列尾巴等候**

因為「完美的」先來先到，可能跟「進入隊列尾巴」

時間上的前後，會有兩種情況

1,2,3,4,5

1匹配2~5皆不合，丟到最尾端

2,3,4,5,1 ，突然插入 6 

2,3,4,5,1,6

或是

1,2,3,4,5

完成5的時候，插入6

1,2,3,4,5,6 

====

所以我目前只確定 1,2,3,4,5,6進入隊列

至少不能先拿2,3,4,5,6互相匹配。

謝謝助教～

**Comment by MROS** [comment]
理解錯誤，以 1, 2, 3, 4, 5 的例子來說：
1 進來時，等待隊列就沒有人了，所以 1 立刻進入等待隊列。
當 2 進來時， 等待隊列中有 1 ，因此 2 馬上就試圖與 1 進行匹配。
假如1, 2 沒有配對成功，2 也推入等待隊列中。
3 進來， 3 先嘗試與 1 匹配，若失敗則再與 2 ，又失敗則再推入等待隊列中。

請注意，等待隊列裡的所有人，彼此都無法匹配，他們就是因此才掉入等待隊列之中。

**Comment by hengzhichin** [comment]
了解！  

謝謝助教！
