### ISSUE TITLE
關於競態關係

### ISSUE THREAD

**Issue by ghost** [SystemProgrammingatNTU/mp4-discussion#31]
助教好
spec裡有一段說

> 一般使用狀況下，使用者正要從「配對中」轉爲「聊天中」，伺服器要送出 matched 指令但客戶端尚未收到的同時，客戶端有可能也會送出 quit 。但測試時保證不會發生，

請問這是不是代表，只要還有某些client的try_match請求還沒處理完(還沒match完整個queue或被加進queue尾端)，
就不會從queue裡的client或try_match尚未的處理完的那些client那裡收到quit?

**Comment by MROS** [comment]
不是，如果我設計篩選函式來保證某個客戶端不會被配對，也就是說此時伺服器不可能發 matched 給這個客戶端，那該客戶端就有可能送出 quit 。

**Comment by ghost** [comment]
所以也有可能某個client的篩選函式正在跑，卻收到他的quit嗎？

**Comment by MROS** [comment]
正是如此。
