### ISSUE TITLE
pid使用問題

### ISSUE THREAD

**Issue by a127000555** [SystemProgrammingatNTU/mp4-discussion#33]
pid使用問題
---
|人物設定||
|-|-|
|username|MAMA|
|filter|while(1);|

|MAMA Script|
|-|
|MAMA try-match (\t)|
|MAMA 正在跟別人做篩選|
|MAMA quit (\q)|
|MAMA 重新 try-match(\t)|
|MAMA quit(\q)|
|MAMA 重新 try-match(\t)|
|重複下去|

#### MAMA quit的時候，能否不送kill singal給child process，只忽略結果即可？
* 如此問的原因是，假設有太多類似情況發生，會導致pid exhaustion。並導致程式無法fork出新的process去處理其他問題。

**Comment by MROS** [comment]
測試資料保證有寫不含無窮迴圈，不需要kill

**Comment by a127000555** [comment]
寫無窮迴圈只是方便，
應該說假設篩選函式要跑10分鐘，
這個人會不會在10分鐘內try match個5萬次之類的

**Comment by MROS** [comment]
簡言之，不需要kill在效能上也不會有問題。

**Comment by MROS** [comment]
還有同一個人處於 配對中 狀態時，不會再發出 try match，這在spec也有提到
