### ISSUE TITLE
Try match and Quit

### ISSUE THREAD

**Issue by tsunghan-wu** [SystemProgrammingatNTU/mp4-discussion#35]
助教請問有關於try match時候quit的保證：
現在我的做法是開兩個list，一個是新進的client，另外一個是前N-1個人都不匹配的waiting list

如果quit的client在waiting list中，我們把他從waiting list中移除，但當下他其實在跟新進的client做配對，這樣fork出去的process回傳回來的時候，由於index大亂，很難辨別是否跟原本的是同一個人，這個我們要做handle嗎？

**Comment by MROS** [comment]
要。你可以不使用 index 來定位，而是使用某種唯一識別子。
