### ISSUE TITLE
JSON逗號格式問題

### ISSUE THREAD

**Issue by y87526** [SystemProgrammingatNTU/mp4-discussion#38]
請問助教，JSON的最後一個項目結尾有保證有逗號或沒有逗號嗎
例如{"cmd":"quit"} 或 {"cmd":"quit",}
說明頁面是兩種都有出現
而cJSON好像直接parse後者會錯，如果出現有逗號的情況我可能要另外判了QQ

**Comment by MROS** [comment]
抱歉筆誤，一律都是前者

**Comment by MROS** [comment]
抱歉筆誤，一律都是前者
