### ISSUE TITLE
Name piped RDWR模式

### ISSUE THREAD

**Issue by tall15421542** [SystemProgrammingatNTU/mp4-discussion#39]
想要請問一下助教name-piped的問題。我目前的狀況是一個process開RDONLY，一個process開WRONLY，他會一直偵測到name pipe可以讀，並一直讀重複的東西出來，好像讀完後沒有從name piped清掉一般。但是改成RDWR就可以改善這個問題，讀一次就不會再讀了，感覺有正常的把name pipe清空。不知道助教對於這樣的現象有沒有看法～因為根據之前助教所說的，這樣的開檔模式是不安全的～

**Comment by MROS** [comment]
可以提供簡單的範例程式碼嗎?這樣我們討論起來比較方便~

**Comment by y87526** [comment]
樓主所謂讀重複的東西出來似乎是因為原本的buffer有舊值
read 0 byte後舊值沒有變，此時去看buffer會看到舊值，所以感覺好像一直讀同樣的東西，實際上沒有
不知道是不是這個原因

**Comment by fsps60312** [comment]
請參考：https://www.facebook.com/CodingSimplifyLife/posts/1997094667227462

**Comment by tall15421542** [comment]
我的程式看起來很正常啊（我覺得啦）下面是範例

以下是開啟name pipe的code

主程式
fork 處理match排程的process
open(OutToChild, O_WRONLY);
open(InFromChild, O_RDONLY);

處理match排程的process
/* 開三個平行處理match的process */
for(int i = 0 ; i < WorkingMatchNum ; i++)
     fork 處理match要求的process
 for(int i = 0 ; i < WorkingMatchNum ; i++)
      open(OutToChild[i], O_WDONLY);
      open(InFromChild[i], O_RDONLY);
/* 創建與server的pipe  打開後把對應的fd存入 */
CreatePipe(input_pipeName, output_pipeName, &InFromParent, &OutToParent); 

處理實際match的process
/* 創建與match排程process溝通的pipe 打開後把對應的fd存入*/
CreatePipe(input_pipeName, output_pipeName, &InFromParent, &OutToParent); 

void CteatePipe(input_pipeName, output_pipeName, &inputfd, &outputfd){
        mkfifo(input_pipeName, 0644);
        mkfifo(output_pipeName, 0644);
        *inputfd = open(input_pipeName, O_RDONLY);
        *outputfd = open(output_pipeName, O_WRONLY);
}

以上是我開設pipe溝通的過程，接下來是收到一個try match請求後，測試的程式碼（與pipe相關的）

主程式
int command = TRYMATCH;
write(OutToChild, &command, sizeof(int));
write(OutToChild, &User_Info, sizeof(struct User_Info));

中介處理match排成的程式
select....
if(FD_ISSET(InFromParent, &workingReadSet))
    int command;  
    read(InFromParent, &command, sizeof(int));
    switch(command){
         case(TRYMATCH)
                 struct User_Info User_Info;
                 read(InFromParent, &User_Info, sizeof(struct User_Info))
                 BroadCast(OutToChild[], User_Info)
                 break;
    }

void BroadCast(int OutToChild[], struct User_Info User_Info){
        for(int i = 0 ; i< WorkingMatchNum;i++){
                   int command = ADDLIST
                   write(OutToChild[i], &command, sizeof(int));
                   wrire(OutToChild[i], &User_Info, sizeof(struct User_Info));
        }
}

實際處理Match的process
select...
if(FD_ISSET(InFromParent)){
          int command;
          read(InFromParent, &command, sizeof(int));
          switch(command){
                 case ADDLIST:{
                          struct User_Info User_Info;
                          read(InFromParent, &User_Info, struct(sizeof(struct User_Info)));
                          PrintUser(User_Info);
                          break;
                 }
          }
}

這個程式的問題是CreatePipe那邊如果按照現在的模式單向打開，那麼處理Match的process會一直select到pipe可以讀，並讀到ADDLIST，和User_Info，並印出來，不斷重複循環。然而如果改成RDＷＲ模式打開pipe，他只會印一次。我最大的問題是，為什麼把模式改成RDWR可以修正這個bug(或者他根本還是有bug但是結果出現跟我預期的剛好一樣) 這個情況應該不是read 0 bytes?  不好意思問題有點長qq

**Comment by MROS** [comment]
首先，建議你用 \`\`\` c 跟 \`\`\` 將程式碼夾住，否則很難閱讀。

還有如果你能做一個能最小重現問題的可執行範例程式，而非只是各個功能的片段，會更易於討論與除錯。

**Comment by MROS** [comment]
想先確認一下，read 0時，應該沒有寫入 buffer ，跟前面同學提到的一樣，只是舊值？

**Comment by tall15421542** [comment]
抱歉抱歉我原本有tab好再傳出去的...然後我剛剛才理解同學的意思，狀況確實是讀了0bytes，雖然是0bytes但是select還是會有反應，判斷過後現在解決了，謝謝同學和助教！
