### ISSUE TITLE
覺得怪怪的

### ISSUE THREAD

**Issue by fsps60312** [SystemProgrammingatNTU/mp4-discussion#4]
所以匹配是找人那方的filter_function有match就好，不需要等人的filter_function也match找人方？

**Comment by MROS** [comment]
必須匹配彼此的篩選函式才算配對成功。
另外，往後下的標題請注意一下，最好能讓人看到標題就大概了解問題內容。「覺得怪怪的」這樣的標題讓往後查看issue的人難以猜想到其與篩選函式匹配的關聯。
