### ISSUE TITLE
是否有 Client 惡意延長傳送

### ISSUE THREAD

**Issue by jd3main** [SystemProgrammingatNTU/mp4-discussion#40]
請問是否會有 client 端傳送 JSON 到一半就刻意暫停，延長傳送時間？
如果是這樣我們需要做到 non-blocking 嗎？
如果需要 Non-blocking 的話，使用 pthread 實作會不會因為同時開 800 個 thread 超過可用的 process 上限？
又，這樣會不會造成記憶體占用太大？

**Comment by MROS** [comment]
用select來做即可。
八百個thread你可以實驗看看，可能在一個模糊地帶，或是透過一些優化可以達成。
