### ISSUE TITLE
cmd內json順序互調的問題

### ISSUE THREAD

**Issue by leo08260826** [SystemProgrammingatNTU/mp4-discussion#41]
SPEC上的send_message長這樣
{
	"cmd": "send_message",
	"message": "Hello!",              // 與請求時一樣的 message
	"sequence": 4,                    // 與請求時一樣的 sequence
}
助教給的client裡面的長這樣
{
	"cmd": "send_message",
        "sequence": 4,                    // 與請求時一樣的 sequence
	"message": "Hello!",              // 與請求時一樣的 message
}
請問cmd的json順序都是不確定的嗎?

**Comment by MROS** [comment]
是不確定的
