### ISSUE TITLE
json 格式

### ISSUE THREAD

**Issue by michael0703** [SystemProgrammingatNTU/mp4-discussion#44]
助教:
    我目前兩個客戶端(A,B)在聊天的時候,第一次傳訊息可以正常的傳送,假設A傳給B,A跟B都看的到訊息,可是第二次傳送訊息(假設B傳給A),就會發生syntax error,可是我有檢查過我傳過去的json字串,是跟第一次是一樣的.然後就會噴說: SyntaxError: Unexpected token in JSON at position 0,然後我就去檢查傳過去的字串的第一個char,是括號沒錯@@,想請問可能是為什麼會這個樣子?我在網路上查好像很多人都有遇到類似的問題,不過目前沒看到甚麼解法@@

**Comment by MROS** [comment]
應該會噴出 SyntaxError: Unexpected token 某個字元 in JSON at position 0
但是你的狀況是沒有顯示任何字元？

**Comment by michael0703** [comment]
我的有顯示一些印不出來的字元
可是server印出的是正常的

**Comment by MROS** [comment]
你使用的客戶端是我提供的嗎？我自己沒有遇到這個問題，有沒有可能你印出跟送到 socket 的字串並不完全相同？

**Comment by tall15421542** [comment]
我也有類似的問題，想請問助教哪裡格式錯了qq
<img width="1440" alt="2017-12-27 6 10 25" src="https://user-images.githubusercontent.com/19918816/34378712-4d695c40-eb32-11e7-9a1e-190f0dc49a79.png">
<img width="620" alt="2017-12-27 6 07 27" src="https://user-images.githubusercontent.com/19918816/34378714-4db5497a-eb32-11e7-8cb1-8e4c9563e5e4.png">

**Comment by tall15421542** [comment]
前面井字號是分隔用的，最後面有記得換行～

**Comment by tall15421542** [comment]
已經解決～～樓主可以看看你第一次傳的訊息後面是否有多傳東西，像我是多傳了一個‘\0'
