### ISSUE TITLE
CPU評測問題

### ISSUE THREAD

**Issue by a127000555** [SystemProgrammingatNTU/mp4-discussion#5]
評分的項目有一項是:
(2 分) 以至少兩倍於單 CPU 的速度處理篩選函式

請問助教是怎麼評測這件事情的呢?

**Comment by MROS** [comment]
我預計放入多個CPU密集的篩選函式（跑一些無意義的運算），這些篩選函式耗時會很長，長到能夠抵消掉 IO 耗損的時間。先行量測這些函式直接執行所需的時間後，再去估算同學的平行化程度。
