### ISSUE TITLE
兩個問題：篩選函式可能無法編譯嗎？編譯工作交給主進程做OK嗎？

### ISSUE THREAD

**Issue by fsps60312** [SystemProgrammingatNTU/mp4-discussion#8]

**Comment by MROS** [comment]
原本並沒有做這個假設，但爲減輕同學負擔，我現在加入這條保證：篩選函式保證能通過編譯。

「編譯工作交給 server」這段話我不是很明白，編譯工作一定是在 server 執行，只不過具體交由哪個進程來執行取決於你的架構是如何分配工作的。

**Comment by fsps60312** [comment]
啊啊抱歉，我原本想的問題是編譯工作全部交給主進程會不會太慢？

**Comment by MROS** [comment]
如果只編譯一次就暫存起來，我估計問題不大。

**Comment by fsps60312** [comment]
那預設執行目錄是MP4底下嗎？
然後執行期間在執行目錄產生一堆.c檔、.so檔、fifo會不會出事？
像這樣：
![image](https://user-images.githubusercontent.com/16624833/34080190-10f5dfc8-e375-11e7-8bd4-5cd4f7c5c172.png)

**Comment by MROS** [comment]
沒事兒沒事兒。我會開一個乾淨的目錄起來編譯你的程式碼，在該目錄底下做事都沒問題。
