### ISSUE TITLE
請問要怎麼測試1000人上線？

### ISSUE THREAD

**Issue by fsps60312** [SystemProgrammingatNTU/mp4-discussion#9]
有2分是這樣的：
(2 分) 支援 1000 人上線、兩秒內 100 條訊息傳遞（無論篩選函式的忙碌程度）
請問這要怎麼測試呢？

**Comment by MROS** [comment]
我會開一隻程式建立一千個連線，同時用已配對成功的連線互相發送訊息並量測時間。

**Comment by fsps60312** [comment]
請問可以把這個程式公布讓我們測試嗎？

**Comment by MROS** [comment]
這個...助教我要拼一下，看下個週末前可不可以弄出來

**Comment by MROS** [comment]
我失敗了，明天再戰。

**Comment by MROS** [comment]
抱歉，實在是力有未逮，明天公佈也太晚了。
但我預計的流程是

1. 先開兩百人使之互相匹配
2. 開六百人使匹配函式陷入忙碌
3. 令某一百人傳輸給另一百人，檢查作爲接收者的一百人是否在兩秒內收到訊息。

希望對您有幫助

**Comment by fsps60312** [comment]
助教，可是您說過編譯工作全數交給主進程並不會有問題耶
開了600人使匹配函式陷入忙碌後，主進程就會卡在編譯工作，這樣根本不會理會message封包啊Orz
是否可以改成：開10人，每人的匹配函式都是要跑很久的(>2秒)，然後再開始讓配好的790人互傳訊息呢？

**Comment by MROS** [comment]
好主意，可以。

**Comment by MROS** [comment]
話說還真是後悔說過這個保證，因為在兩倍速度的測試中可以，但是兩秒傳100的預設考量應該要不行，唉...

**Comment by fsps60312** [comment]
助教您大可直接告訴我們 我們可以怎麼設計架構，「2秒內傳100封訊息，無論篩選函式忙碌程度」，訊息還是稍嫌不足......
每一項限制被補充，我們多少人因為架構設計本身不支援，要把專案整個打掉重新改寫，助教您知道嗎......？500行的code耶
也希望下一次的助教，至少先寫好個簡單的judge讓我們測試，我們才猜得到，你們要考我們的是甚麼？
不然，我們很難通靈，只能問一堆問題希望有確認到所有可能，助教也會為了回答各種看似很基本的問題而增加工作量
雖然說，只剩下一次作業了，我個人其實也沒有很在意了（我不是最在意的那位，但算是最勇於幫大家表達意見的那位）。只是，大家的心聲，希望還是可以傳達出來，讓下一屆的學弟妹，不要再被為難
對了補充一下這次助教其實還不錯，不是在說您XD

**Comment by MROS** [comment]
設計這麼大的作業所需要的功夫超乎了我的預期，頂着研究生修課、做計劃的壓力，再加上不間斷的解答同學們的問題，遲遲趕不及完成範例主程式與測試程式，確實在回答「這個可在主程式編譯」的問題，產生了失誤。

然而本次應該沒有其他補充的限制（要求送出 socket fail\n 不至於更動架構），我修改的限制全部都是調寬，也就是完全向前兼容的。而我在「測試時的保證」中沒有保證的，同學們自然必須自行考量到。

之所以不直接告訴各位架構，是希望同學們能夠自行設計架構，在多種可能之間去蕪存菁，最終提煉出能夠符合需求的架構，是很寶貴的經驗。不管是自己想要設計的程式、或是接收委託、上級交付的任務，都是以「需求」作爲第一層介面，底下的架構，必須透過審視需求來進行設計。

我不希望設計一個架構很死的作業，而是希望作業好像是一個真實世界中會出現的一個程式，（當然還得讓同學們練習到課堂上所學到的新知識），因爲我認爲這樣比較不會有斧鑿痕跡，更接近軟體開發的真實狀況。

judge 程式方面，我很難評斷到底應該提前釋出還是不釋出，釋出對同學的分數提升有一定幫助，但另一方面同學也應該去學習如何自行去檢驗程式的正確性，而要釋出一支成熟精良的測試程式，亦是一個很大的負擔，有時候實在力不從心，上次是遇到了國慶假期，我才能即時釋出。

MP5 的難度不高，所以類似的問題應該會少得多，明年助教也會換人，您的意見會在交接時會反映給下一任。

**Comment by jerry73204** [comment]
@fsps60312 我們從你的意見受惠不少。@MROS 已經用去不少時間在設計這個作業，也親自寫了不同版本實作，同樣發現限制上有不合理處我們也會從寬認定，也會考量更改標準的時機重新調整評測方式。
至於離線評測，雖然嚴格說不是助教的義務，也無法保證明年的助教也會做，不過考慮到減輕作業分數的負擔，一有機會我們會想辦法釋出，也請體諒一下助教必須在期末考週時候生一個 judge 出來。畢竟要做出可以支援多個進/線程、考慮到所有 case 的評測程式難度不輸作業本身，能否如期完成本身就有變數，基於信用上我們不能掛保證，請同學見諒。

**Comment by fsps60312** [comment]
這幾次作業對我來說是真的滿好玩的，也真的學到不少（不管是架構設計、library使用，還是專案管理技巧），謝謝助教們，其實我做得很開心，也超有成就感XD

(方法一)
> 只是這些作業真的需要花費大量時間，對某些同學而言稍微太多了一點。或許可以考慮對同一個(或2個)專案用插件的方式每次加入新功能？不然考量到要抉擇在這個作業上花多少時間，是要先砸很多時間弄一個比較好的架構呢？還是先隨便弄出一個看起來沒動歪的東西就好？我想如果一個學期中不要有那麼多專案，選擇前者的意願會比較高吧

這是我個人的看法啦

我是真的很喜歡每次的作業哦！ <3
助教們的辛苦我多少也可以體會，只是覺得在同一門課中出這麼多作業滿不可思議哈哈哈（以我的能力而言（而且我不會去在意GPA投資報酬率之類的事情），其實還滿喜歡這樣的模式XD）

(方法二)
> 如果離線judge可以提前釋出，我相信問題是真的會少很多啦，對減輕雙方負擔也有正面影響。而且，提前釋出judge應該不會加重整體負擔(?)（只是把一些事情挪到前面的時間先完成？）

**Comment by MROS** [comment]
感謝你的肯定，方法一可以考慮，其實我們在設計作業的過程中也有考慮過，把作業漸次增強最後作出一個功能很強的程式，但中途故事接不起來，只好作罷，往後可以試着修改本次設計的作業，來往這個方向邁進。

方法二的話，說總體負擔不會加重，但是我們也不能說同學們的寫作業時間都縮短到三天，反正總體負擔不會加重吧。當然如果未來的的助教沿用作業，那負擔減輕，釋出 judge 的可能性也會增加。
